// React Native AISummaryCard Component
// Displays AI-generated review summary with beautiful design

import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { Spacing, FontSize, BorderRadius, FontWeight, Shadow, Glass, Glow, Gradients } from '../constants/theme';
import { useTheme } from '../context/ThemeContext';

interface AISummaryCardProps {
  summary: string;
}

export const AISummaryCard: React.FC<AISummaryCardProps> = ({ summary }) => {
  const { colors, colorScheme } = useTheme();

  // Debug log
  console.log('AISummaryCard rendering with summary:', summary?.substring(0, 50));

  if (!summary || summary.trim().length === 0) {
    console.warn('AISummaryCard: No summary provided');
    return null;
  }

  return (
    <View style={[styles.container, colorScheme === 'dark' ? Glass.card : Glass.cardLight, Glow.ai]}>
      {/* Visible top shine gradient */}
      <LinearGradient
        colors={['rgba(139,92,246,0.20)', 'rgba(99,102,241,0.08)', 'transparent']}
        start={{ x: 0, y: 0 }}
        end={{ x: 0, y: 1 }}
        style={styles.cardShine}
      />

      {/* Top edge highlight */}
      <LinearGradient
        colors={['rgba(139,92,246,0.5)', 'rgba(99,102,241,0.3)', 'transparent']}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 0 }}
        style={styles.topEdge}
      />

      {/* Header with AI badge */}
      <View style={styles.header}>
        <LinearGradient
          colors={Gradients.ai as [string, string]}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.aiBadge}
        >
          <Ionicons name="sparkles" size={16} color="#fff" />
          <Text style={styles.aiBadgeText}>AI Summary</Text>
        </LinearGradient>
      </View>

      {/* Summary text */}
      <Text style={[styles.summaryText, { color: colors.foreground }]}>
        {summary}
      </Text>

      {/* Footer note */}
      <View style={[styles.footer, colorScheme === 'dark' ? Glass.subtle : { backgroundColor: colors.secondary }]}>
        <Ionicons name="information-circle-outline" size={14} color={colors.mutedForeground} />
        <Text style={[styles.footerText, { color: colors.mutedForeground }]}>
          Generated by AI based on customer reviews
        </Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    borderRadius: BorderRadius['2xl'],
    padding: Spacing.xl,
    overflow: 'hidden',
    ...Shadow.medium,
    position: 'relative',
  },
  cardShine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 80,
  },
  topEdge: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.lg,
  },

  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    ...Shadow.soft,
  },

  aiBadgeText: {
    color: '#fff',
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  summaryText: {
    fontSize: FontSize.base,
    lineHeight: FontSize.base * 1.7,
    marginBottom: Spacing.lg,
  },

  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
  },

  footerText: {
    fontSize: FontSize.xs,
    fontStyle: 'italic',
  },
});
